# Generated by Django 4.1.3 on 2022-11-28 06:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='is_true',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('user', 'quiz', 'question', 'option')},
        ),
    ]
